import { CoordsTuple } from "../tile/tile.types";

export const enum DecoType {
    MUSHROOM_S,
    MUSHROOM_M,
    MUSHROOM_L,
    STONE_S,
    STONE_M,
    STONE_L,
    BUSH_S,
    BUSH_M,
    BUSH_L,
    WEED_S,
    WEED_M,
    PUMPKIN_S,
    PUMPKIN_M,
    BONE_S,
    BONE_M,
    SIGN_STOP_TOP,
    SIGN_STOP_BOTTOM,
    SIGN_RIGHT_TOP,
    SIGN_RIGHT_BOTTOM,
    SCARECROW,
}

export const mapTerrainToCoords: Record<DecoType, CoordsTuple> = {
    [DecoType.MUSHROOM_S]: [0, 0],
    [DecoType.MUSHROOM_M]: [0, 0],
    [DecoType.MUSHROOM_L]: [0, 0],
    [DecoType.STONE_S]: [0, 0],
    [DecoType.STONE_M]: [0, 0],
    [DecoType.STONE_L]: [0, 0],
    [DecoType.BUSH_L]: [0, 0],
    [DecoType.BUSH_S]: [0, 0],
    [DecoType.BUSH_M]: [0, 0],
    [DecoType.WEED_S]: [0, 0],
    [DecoType.WEED_M]: [0, 0],
    [DecoType.PUMPKIN_S]: [0, 0],
    [DecoType.PUMPKIN_M]: [0, 0],
    [DecoType.BONE_S]: [0, 0],
    [DecoType.BONE_M]: [0, 0],
    [DecoType.SIGN_STOP_TOP]: [0, 0],
    [DecoType.SIGN_STOP_BOTTOM]: [0, 64],
    [DecoType.SIGN_RIGHT_TOP]: [0, 0],
    [DecoType.SIGN_RIGHT_BOTTOM]: [0, 64],
    [DecoType.SCARECROW]: [0, 0],
};
