import { LayerRules, SpriteWeight } from "@core/layer";
import { SpriteName } from "@core/renderer";

export const GROUND_WEIGHT: SpriteWeight[] = [
  [SpriteName.WATER_MIDDLE_MIDDLE,  1, true],

  [SpriteName.GROUND_TOP_LEFT,      10, false],
  [SpriteName.GROUND_TOP_MIDDLE,    10, false],
  [SpriteName.GROUND_TOP_RIGHT,     10, false],
  [SpriteName.GROUND_MIDDLE_LEFT,   10, false],
  [SpriteName.GROUND_MIDDLE_MIDDLE, 100, false],
  [SpriteName.GROUND_MIDDLE_RIGHT,  10, false],
  [SpriteName.GROUND_BOTTOM_LEFT,   10, false],
  [SpriteName.GROUND_BOTTOM_MIDDLE, 10, false],
  [SpriteName.GROUND_BOTTOM_RIGHT,  10, false],

  [SpriteName.BRIDGE_LEFT,          10, false],
  [SpriteName.BRIDGE_MIDDLE,        10, false],
  [SpriteName.BRIDGE_RIGHT,         10, false],

  [SpriteName.TREE_STRUMP,          2, true],
];

export const GROUND_RULES: LayerRules = {
  [SpriteName.WATER_MIDDLE_MIDDLE]: [
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.BRIDGE_MIDDLE,
    ],
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_BOTTOM_LEFT,
    ],
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.BRIDGE_MIDDLE,
    ],
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
  ],
  [SpriteName.GROUND_TOP_LEFT]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
  ],
  [SpriteName.GROUND_TOP_MIDDLE]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.TREE_STRUMP,
    ],
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [SpriteName.GROUND_TOP_RIGHT]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.BRIDGE_LEFT,
    ],
  ],
  [SpriteName.GROUND_MIDDLE_LEFT]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.BRIDGE_LEFT,
      SpriteName.TREE_STRUMP,
    ],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
  ],
  [SpriteName.GROUND_MIDDLE_MIDDLE]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.TREE_STRUMP,
    ],
    [
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.BRIDGE_LEFT,
      SpriteName.TREE_STRUMP,
    ],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.TREE_STRUMP,
    ],
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.BRIDGE_RIGHT,
      SpriteName.TREE_STRUMP,
    ],
  ],
  [SpriteName.GROUND_MIDDLE_RIGHT]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.BRIDGE_RIGHT,
      SpriteName.TREE_STRUMP,
    ],
  ],
  [SpriteName.GROUND_BOTTOM_LEFT]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.WATER_MIDDLE_MIDDLE],
  ],
  [SpriteName.GROUND_BOTTOM_MIDDLE]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.TREE_STRUMP,
    ],
    [
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [SpriteName.GROUND_BOTTOM_RIGHT]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_TOP_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_BOTTOM_LEFT,
      SpriteName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [SpriteName.BRIDGE_LEFT]: [
    [
      SpriteName.GROUND_TOP_RIGHT,
      SpriteName.GROUND_MIDDLE_RIGHT,
    ],
    [SpriteName.BRIDGE_MIDDLE],
    [
      SpriteName.GROUND_MIDDLE_RIGHT,
      SpriteName.GROUND_BOTTOM_RIGHT,
    ],
    [
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_LEFT,
    ],
  ],
  [SpriteName.BRIDGE_MIDDLE]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.BRIDGE_MIDDLE, SpriteName.BRIDGE_RIGHT],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.BRIDGE_MIDDLE, SpriteName.BRIDGE_LEFT],
  ],
  [SpriteName.BRIDGE_RIGHT]: [
    [
      SpriteName.GROUND_TOP_LEFT,
      SpriteName.GROUND_MIDDLE_LEFT,
    ],
    [
      SpriteName.GROUND_MIDDLE_MIDDLE,
      SpriteName.GROUND_MIDDLE_RIGHT,
    ],
    [
      SpriteName.GROUND_MIDDLE_LEFT,
      SpriteName.GROUND_BOTTOM_LEFT,
    ],
    [
      SpriteName.BRIDGE_MIDDLE,
      SpriteName.BRIDGE_LEFT
    ],
  ],
  [SpriteName.TREE_STRUMP]: [
    [SpriteName.GROUND_TOP_MIDDLE, SpriteName.GROUND_MIDDLE_MIDDLE],
    [SpriteName.GROUND_MIDDLE_RIGHT, SpriteName.GROUND_MIDDLE_MIDDLE],
    [SpriteName.GROUND_BOTTOM_MIDDLE, SpriteName.GROUND_MIDDLE_MIDDLE],
    [SpriteName.GROUND_MIDDLE_LEFT, SpriteName.GROUND_MIDDLE_MIDDLE],
  ],
};