import { ElevationTile } from "../elevation/elevation";
import { ElevationType } from "../elevation/elevation.const";
import { GroundTile } from "../ground/ground";
import { GroundType } from "../ground/ground.const";
import { SandTile } from "../sand/sand";
import { SandType } from "../sand/sand.const";
import { FoamTile } from "../foam/foam";
import { FoamType } from "../foam/foam.const";
import { WaterTile } from "../water/water";
import { BridgeTile } from "../bridge/bridge";
import { BridgeType } from "../bridge/bridge.const";
import { DecoTile } from "../deco/deco";
import { DecoType } from "../deco/deco.const";

export const enum TileName {
  SAND_TOP_LEFT,
  SAND_TOP_MIDDLE,
  SAND_TOP_RIGHT,
  SAND_BOTTOM_LEFT,
  SAND_BOTTOM_MIDDLE,
  SAND_BOTTOM_RIGHT,
  SAND_MIDDLE_LEFT,
  SAND_MIDDLE_MIDDLE,
  SAND_MIDDLE_RIGHT,
  SAND_HORIZONTAL_LEFT,
  SAND_HORIZONTAL_MIDDLE,
  SAND_HORIZONTAL_RIGHT,
  SAND_VERTICAL_TOP,
  SAND_VERTICAL_MIDDLE,
  SAND_VERTICAL_BOTTOM,

  GROUND_TOP_LEFT,
  GROUND_TOP_MIDDLE,
  GROUND_TOP_RIGHT,
  GROUND_BOTTOM_LEFT,
  GROUND_BOTTOM_MIDDLE,
  GROUND_BOTTOM_RIGHT,
  GROUND_MIDDLE_LEFT,
  GROUND_MIDDLE_MIDDLE,
  GROUND_MIDDLE_RIGHT,
  GROUND_HORIZONTAL_LEFT,
  GROUND_HORIZONTAL_MIDDLE,
  GROUND_HORIZONTAL_RIGHT,
  GROUND_VERTICAL_TOP,
  GROUND_VERTICAL_MIDDLE,
  GROUND_VERTICAL_BOTTOM,

  ELEVATION_TOP_LEFT,
  ELEVATION_TOP_MIDDLE,
  ELEVATION_TOP_RIGHT,
  ELEVATION_BOTTOM_LEFT,
  ELEVATION_BOTTOM_MIDDLE,
  ELEVATION_BOTTOM_RIGHT,
  ELEVATION_MIDDLE_LEFT,
  ELEVATION_MIDDLE_MIDDLE,
  ELEVATION_MIDDLE_RIGHT,
  ELEVATION_HORIZONTAL_LEFT,
  ELEVATION_HORIZONTAL_MIDDLE,
  ELEVATION_HORIZONTAL_RIGHT,
  ELEVATION_VERTICAL_TOP,
  ELEVATION_VERTICAL_MIDDLE,
  ELEVATION_VERTICAL_BOTTOM,
  ELEVATION_VERTICAL_EDGE,
  ELEVATION_EDGE_LEFT,
  ELEVATION_EDGE_MIDDLE,
  ELEVATION_EDGE_RIGHT,

  FOAM_TOP,
  FOAM_LEFT,
  FOAM_RIGHT,
  FOAM_BOTTOM,
  FOAM_MIDDLE,

  WATER_MIDDLE_MIDDLE,

  BRIDGE_LEFT,
  BRIDGE_MIDDLE,
  BRIDGE_RIGHT,
  BRIDGE_SHADOW,

  DECO_MUSHROOM_S,
  DECO_MUSHROOM_M,
  DECO_MUSHROOM_L,
  DECO_STONE_S,
  DECO_STONE_M,
  DECO_STONE_L,
  DECO_BUSH_S,
  DECO_BUSH_M,
  DECO_BUSH_L,
  DECO_WEED_S,
  DECO_WEED_M,
  DECO_PUMPKIN_S,
  DECO_PUMPKIN_M,
  DECO_BONE_S,
  DECO_BONE_M,
  DECO_SIGN_STOP,
  DECO_SIGH_RIGHT,
  DECO_SCARECROW,
};

export const mapTileNameToClass: Partial<Record<TileName, { constructor: any, args: Array<any> }>> = {
  [TileName.SAND_TOP_LEFT]: { constructor: SandTile, args: [SandType.TOP_LEFT] },
  [TileName.SAND_TOP_MIDDLE]: { constructor: SandTile, args: [SandType.TOP_MIDDLE] },
  [TileName.SAND_TOP_RIGHT]: { constructor: SandTile, args: [SandType.TOP_RIGHT] },
  [TileName.SAND_BOTTOM_LEFT]: { constructor: SandTile, args: [SandType.BOTTOM_LEFT] },
  [TileName.SAND_BOTTOM_MIDDLE]: { constructor: SandTile, args: [SandType.BOTTOM_MIDDLE] },
  [TileName.SAND_BOTTOM_RIGHT]: { constructor: SandTile, args: [SandType.BOTTOM_RIGHT] },
  [TileName.SAND_MIDDLE_LEFT]: { constructor: SandTile, args: [SandType.MIDDLE_LEFT] },
  [TileName.SAND_MIDDLE_MIDDLE]: { constructor: SandTile, args: [SandType.MIDDLE_MIDDLE] },
  [TileName.SAND_MIDDLE_RIGHT]: { constructor: SandTile, args: [SandType.MIDDLE_RIGHT] },
  [TileName.SAND_VERTICAL_TOP]: { constructor: SandTile, args: [SandType.VERTICAL_TOP] },
  [TileName.SAND_VERTICAL_MIDDLE]: { constructor: SandTile, args: [SandType.VERTICAL_MIDDLE] },
  [TileName.SAND_VERTICAL_BOTTOM]: { constructor: SandTile, args: [SandType.VERTICAL_BOTTOM] },
  [TileName.SAND_HORIZONTAL_LEFT]: { constructor: SandTile, args: [SandType.HORIZONTAL_LEFT] },
  [TileName.SAND_HORIZONTAL_MIDDLE]: { constructor: SandTile, args: [SandType.HORIZONTAL_MIDDLE] },
  [TileName.SAND_HORIZONTAL_RIGHT]: { constructor: SandTile, args: [SandType.HORIZONTAL_RIGHT] },

  [TileName.GROUND_TOP_LEFT]: { constructor: GroundTile, args: [GroundType.TOP_LEFT] },
  [TileName.GROUND_TOP_MIDDLE]: { constructor: GroundTile, args: [GroundType.TOP_MIDDLE] },
  [TileName.GROUND_TOP_RIGHT]: { constructor: GroundTile, args: [GroundType.TOP_RIGHT] },
  [TileName.GROUND_BOTTOM_LEFT]: { constructor: GroundTile, args: [GroundType.BOTTOM_LEFT] },
  [TileName.GROUND_BOTTOM_MIDDLE]: { constructor: GroundTile, args: [GroundType.BOTTOM_MIDDLE] },
  [TileName.GROUND_BOTTOM_RIGHT]: { constructor: GroundTile, args: [GroundType.BOTTOM_RIGHT] },
  [TileName.GROUND_MIDDLE_LEFT]: { constructor: GroundTile, args: [GroundType.MIDDLE_LEFT] },
  [TileName.GROUND_MIDDLE_MIDDLE]: { constructor: GroundTile, args: [GroundType.MIDDLE_MIDDLE] },
  [TileName.GROUND_MIDDLE_RIGHT]: { constructor: GroundTile, args: [GroundType.MIDDLE_RIGHT] },
  [TileName.GROUND_HORIZONTAL_LEFT]: { constructor: GroundTile, args: [GroundType.HORIZONTAL_LEFT] },
  [TileName.GROUND_HORIZONTAL_MIDDLE]: { constructor: GroundTile, args: [GroundType.HORIZONTAL_MIDDLE] },
  [TileName.GROUND_HORIZONTAL_RIGHT]: { constructor: GroundTile, args: [GroundType.HORIZONTAL_RIGHT] },
  [TileName.GROUND_VERTICAL_TOP]: { constructor: GroundTile, args: [GroundType.VERTICAL_TOP] },
  [TileName.GROUND_VERTICAL_MIDDLE]: { constructor: GroundTile, args: [GroundType.VERTICAL_MIDDLE] },
  [TileName.GROUND_VERTICAL_BOTTOM]: { constructor: GroundTile, args: [GroundType.VERTICAL_BOTTOM] },

  [TileName.ELEVATION_TOP_LEFT]: { constructor: ElevationTile, args: [ElevationType.TOP_LEFT] },
  [TileName.ELEVATION_TOP_MIDDLE]: { constructor: ElevationTile, args: [ElevationType.TOP_MIDDLE] },
  [TileName.ELEVATION_TOP_RIGHT]: { constructor: ElevationTile, args: [ElevationType.TOP_RIGHT] },
  [TileName.ELEVATION_BOTTOM_LEFT]: { constructor: ElevationTile, args: [ElevationType.BOTTOM_LEFT] },
  [TileName.ELEVATION_BOTTOM_MIDDLE]: { constructor: ElevationTile, args: [ElevationType.BOTTOM_MIDDLE] },
  [TileName.ELEVATION_BOTTOM_RIGHT]: { constructor: ElevationTile, args: [ElevationType.BOTTOM_RIGHT] },
  [TileName.ELEVATION_MIDDLE_LEFT]: { constructor: ElevationTile, args: [ElevationType.MIDDLE_LEFT] },
  [TileName.ELEVATION_MIDDLE_MIDDLE]: { constructor: ElevationTile, args: [ElevationType.MIDDLE_MIDDLE] },
  [TileName.ELEVATION_MIDDLE_RIGHT]: { constructor: ElevationTile, args: [ElevationType.MIDDLE_RIGHT] },
  [TileName.ELEVATION_HORIZONTAL_LEFT]: { constructor: ElevationTile, args: [ElevationType.HORIZONTAL_LEFT] },
  [TileName.ELEVATION_HORIZONTAL_MIDDLE]: { constructor: ElevationTile, args: [ElevationType.HORIZONTAL_MIDDLE] },
  [TileName.ELEVATION_HORIZONTAL_RIGHT]: { constructor: ElevationTile, args: [ElevationType.HORIZONTAL_RIGHT] },
  [TileName.ELEVATION_VERTICAL_TOP]: { constructor: ElevationTile, args: [ElevationType.VERTICAL_TOP] },
  [TileName.ELEVATION_VERTICAL_MIDDLE]: { constructor: ElevationTile, args: [ElevationType.VERTICAL_MIDDLE] },
  [TileName.ELEVATION_VERTICAL_BOTTOM]: { constructor: ElevationTile, args: [ElevationType.VERTICAL_BOTTOM] },
  [TileName.ELEVATION_VERTICAL_EDGE]: { constructor: ElevationTile, args: [ElevationType.VERTICAL_EDGE] },
  [TileName.ELEVATION_EDGE_LEFT]: { constructor: ElevationTile, args: [ElevationType.EDGE_LEFT] },
  [TileName.ELEVATION_EDGE_MIDDLE]: { constructor: ElevationTile, args: [ElevationType.EDGE_MIDDLE] },
  [TileName.ELEVATION_EDGE_RIGHT]: { constructor: ElevationTile, args: [ElevationType.EDGE_RIGHT] },

  [TileName.FOAM_TOP]: { constructor: FoamTile, args: [FoamType.TOP] },
  [TileName.FOAM_LEFT]: { constructor: FoamTile, args: [FoamType.LEFT] },
  [TileName.FOAM_RIGHT]: { constructor: FoamTile, args: [FoamType.RIGHT] },
  [TileName.FOAM_BOTTOM]: { constructor: FoamTile, args: [FoamType.BOTTOM] },
  [TileName.FOAM_MIDDLE]: { constructor: FoamTile, args: [FoamType.MIDDLE] },

  [TileName.WATER_MIDDLE_MIDDLE]: { constructor: WaterTile, args: [] },

  [TileName.BRIDGE_LEFT]: { constructor: BridgeTile, args: [BridgeType.LEFT] },
  [TileName.BRIDGE_MIDDLE]: { constructor: BridgeTile, args: [BridgeType.MIDDLE] },
  [TileName.BRIDGE_RIGHT]: { constructor: BridgeTile, args: [BridgeType.RIGHT] },
  [TileName.BRIDGE_SHADOW]: { constructor: BridgeTile, args: [BridgeType.SHADOW] },

  [TileName.DECO_MUSHROOM_S]: { constructor: DecoTile, args: [DecoType.MUSHROOM_S] },
  [TileName.DECO_MUSHROOM_M]: { constructor: DecoTile, args: [DecoType.MUSHROOM_M] },
  [TileName.DECO_MUSHROOM_L]: { constructor: DecoTile, args: [DecoType.MUSHROOM_L] },
  [TileName.DECO_STONE_S]: { constructor: DecoTile, args: [DecoType.STONE_S] },
  [TileName.DECO_STONE_M]: { constructor: DecoTile, args: [DecoType.STONE_M] },
  [TileName.DECO_STONE_L]: { constructor: DecoTile, args: [DecoType.STONE_L] },
  [TileName.DECO_BUSH_S]: { constructor: DecoTile, args: [DecoType.BUSH_S] },
  [TileName.DECO_BUSH_M]: { constructor: DecoTile, args: [DecoType.BUSH_M] },
  [TileName.DECO_BUSH_L]: { constructor: DecoTile, args: [DecoType.BUSH_L] },
  [TileName.DECO_WEED_S]: { constructor: DecoTile, args: [DecoType.WEED_S] },
  [TileName.DECO_WEED_M]: { constructor: DecoTile, args: [DecoType.WEED_M] },
  [TileName.DECO_PUMPKIN_S]: { constructor: DecoTile, args: [DecoType.PUMPKIN_S] },
  [TileName.DECO_PUMPKIN_M]: { constructor: DecoTile, args: [DecoType.PUMPKIN_M] },
  [TileName.DECO_BONE_S]: { constructor: DecoTile, args: [DecoType.BONE_S] },
  [TileName.DECO_BONE_M]: { constructor: DecoTile, args: [DecoType.BONE_M] },
  [TileName.DECO_SIGN_STOP]: { constructor: DecoTile, args: [DecoType.SIGN_STOP] },
  [TileName.DECO_SIGH_RIGHT]: { constructor: DecoTile, args: [DecoType.SIGH_RIGHT] },
  [TileName.DECO_SCARECROW]: { constructor: DecoTile, args: [DecoType.SCARECROW] },
};