import { LayerRules, LayerWight } from "../../../../layer/layer.types";
import { TileName } from "../../../../renderer";

export const GROUND_WEIGHT: LayerWight = [
  [TileName.WATER_MIDDLE_MIDDLE,  1, true],

  [TileName.GROUND_TOP_LEFT,      10, false],
  [TileName.GROUND_TOP_MIDDLE,    10, false],
  [TileName.GROUND_TOP_RIGHT,     10, false],
  [TileName.GROUND_MIDDLE_LEFT,   10, false],
  [TileName.GROUND_MIDDLE_MIDDLE, 100, false],
  [TileName.GROUND_MIDDLE_RIGHT,  10, false],
  [TileName.GROUND_BOTTOM_LEFT,   10, false],
  [TileName.GROUND_BOTTOM_MIDDLE, 10, false],
  [TileName.GROUND_BOTTOM_RIGHT,  10, false],

  [TileName.BRIDGE_LEFT,          10, false],
  [TileName.BRIDGE_MIDDLE,        10, false],
  [TileName.BRIDGE_RIGHT,         10, false],

  [TileName.TREE_STRUMP,          2, true],
];

export const GROUND_RULES: LayerRules = {
  [TileName.WATER_MIDDLE_MIDDLE]: [
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_MIDDLE,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_BOTTOM_LEFT,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.BRIDGE_MIDDLE,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
  ],
  [TileName.GROUND_TOP_LEFT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_TOP_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.GROUND_TOP_RIGHT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_LEFT,
    ],
  ],
  [TileName.GROUND_MIDDLE_LEFT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_MIDDLE_MIDDLE]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_RIGHT,
      TileName.TREE_STRUMP,
    ],
  ],
  [TileName.GROUND_MIDDLE_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_RIGHT,
      TileName.TREE_STRUMP,
    ],
  ],
  [TileName.GROUND_BOTTOM_LEFT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_BOTTOM_MIDDLE]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.GROUND_BOTTOM_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.BRIDGE_LEFT]: [
    [
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [TileName.BRIDGE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
    ],
  ],
  [TileName.BRIDGE_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.BRIDGE_MIDDLE, TileName.BRIDGE_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.BRIDGE_MIDDLE, TileName.BRIDGE_LEFT],
  ],
  [TileName.BRIDGE_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_MIDDLE_LEFT,
    ],
    [
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_BOTTOM_LEFT,
    ],
    [
      TileName.BRIDGE_MIDDLE,
      TileName.BRIDGE_LEFT
    ],
  ],
  [TileName.TREE_STRUMP]: [
    [TileName.GROUND_TOP_MIDDLE, TileName.GROUND_MIDDLE_MIDDLE],
    [TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
    [TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_MIDDLE_MIDDLE],
    [TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
  ],
};