import { CoordsTuple } from '../tile/tile.types';

export const enum DecoType {
  MUSHROOM_S,
  MUSHROOM_M,
  MUSHROOM_L,
  STONE_S,
  STONE_M,
  STONE_L,
  BUSH_S,
  BUSH_M,
  BUSH_L,
  WEED_S,
  WEED_M,
  PUMPKIN_S,
  PUMPKIN_M,
  BONE_S_RIGHT,
  BONE_S_LEFT,
  BONE_M_LEFT,
  BONE_M_RIGHT,
  SIGN_STOP_TOP,
  SIGN_STOP_BOTTOM,
  SIGH_RIGHT_TOP,
  SIGH_RIGHT_BOTTOM,
  SCARECROW,
  SKULL_RIGHT,
  SKULL_LEFT,
}

export const enum DecoAnimation {
  FORWARD = 'FORWARD',
  BACKWARD = 'BACKWARD',
  WEAK_ATTACK = 'WEAK_ATTACK',
  STRONG_ATTACK = 'STRONG_ATTACK',
}

export const mapTerrainToCoords: Record<DecoType, CoordsTuple> = {
  [DecoType.MUSHROOM_S]: [0, 0],
  [DecoType.MUSHROOM_M]: [0, 0],
  [DecoType.MUSHROOM_L]: [0, 0],
  [DecoType.STONE_S]: [0, 0],
  [DecoType.STONE_M]: [0, 0],
  [DecoType.STONE_L]: [0, 0],
  [DecoType.BUSH_L]: [0, 0],
  [DecoType.BUSH_S]: [0, 0],
  [DecoType.BUSH_M]: [0, 0],
  [DecoType.WEED_S]: [0, 0],
  [DecoType.WEED_M]: [0, 0],
  [DecoType.PUMPKIN_S]: [0, 0],
  [DecoType.PUMPKIN_M]: [0, 0],
  [DecoType.BONE_S_RIGHT]: [0, 0],
  [DecoType.BONE_S_LEFT]: [0, 64],
  [DecoType.BONE_M_RIGHT]: [0, 0],
  [DecoType.BONE_M_LEFT]: [0, 64],
  [DecoType.SIGN_STOP_TOP]: [0, 0],
  [DecoType.SIGN_STOP_BOTTOM]: [0, 64],
  [DecoType.SIGH_RIGHT_TOP]: [0, 0],
  [DecoType.SIGH_RIGHT_BOTTOM]: [0, 64],
  [DecoType.SCARECROW]: [0, 0],
  [DecoType.SKULL_RIGHT]: [0, 0],
  [DecoType.SKULL_LEFT]: [64, 0],
};
