import { TileName } from "../../entites/scene/scene.const";

export const TILE_TYPES = [
  TileName.WATER_MIDDLE_MIDDLE,
  TileName.GROUND_TOP_LEFT,
  TileName.GROUND_TOP_MIDDLE,
  TileName.GROUND_TOP_RIGHT,
  TileName.GROUND_MIDDLE_LEFT,
  TileName.GROUND_MIDDLE_MIDDLE,
  TileName.GROUND_MIDDLE_RIGHT,
  TileName.GROUND_BOTTOM_LEFT,
  TileName.GROUND_BOTTOM_MIDDLE,
  TileName.GROUND_BOTTOM_RIGHT,
  TileName.BRIDGE_LEFT,
  TileName.BRIDGE_MIDDLE,
  TileName.BRIDGE_RIGHT,
];

export const TILE_WEIGHT = [
  [TileName.WATER_MIDDLE_MIDDLE,  5],
  [TileName.GROUND_TOP_LEFT,      10],
  [TileName.GROUND_TOP_MIDDLE,    10],
  [TileName.GROUND_TOP_RIGHT,     10],
  [TileName.GROUND_MIDDLE_LEFT,   10],
  [TileName.GROUND_MIDDLE_MIDDLE, 10],
  [TileName.GROUND_MIDDLE_RIGHT,  10],
  [TileName.GROUND_BOTTOM_LEFT,   10],
  [TileName.GROUND_BOTTOM_MIDDLE, 10],
  [TileName.GROUND_BOTTOM_RIGHT,  10],
  [TileName.BRIDGE_LEFT,          40],
  [TileName.BRIDGE_MIDDLE,        40],
  [TileName.BRIDGE_RIGHT,         40],
];

export const TILE_DECO_WEIGHT = [
  [TileName.DECO_MUSHROOM_S, 10],
  [TileName.DECO_MUSHROOM_M, 5],
  [TileName.DECO_MUSHROOM_L, 1],
  [TileName.DECO_STONE_S,    10],
  [TileName.DECO_STONE_M,    5],
  [TileName.DECO_STONE_L,    1],
  [TileName.DECO_BUSH_S,     10],
  [TileName.DECO_BUSH_M,     5],
  [TileName.DECO_BUSH_L,     1],
  [TileName.DECO_PUMPKIN_S,  5],
  [TileName.DECO_PUMPKIN_M,  1],
  [TileName.DECO_WEED_S,     10],
  [TileName.DECO_WEED_M,     5],
];

// export const RULES = {
//   [TileName.WATER_MIDDLE_MIDDLE]: [
//     [
//       TileName.WATER_MIDDLE_MIDDLE,
//       TileName.GROUND_BOTTOM_LEFT,
//       TileName.GROUND_BOTTOM_MIDDLE,
//       TileName.GROUND_BOTTOM_RIGHT,
//     ],
//     [
//       TileName.WATER_MIDDLE_MIDDLE,
//       TileName.GROUND_TOP_LEFT,
//       TileName.GROUND_MIDDLE_LEFT,
//       TileName.GROUND_BOTTOM_LEFT,
//     ],
//     [
//       TileName.WATER_MIDDLE_MIDDLE,
//       TileName.GROUND_TOP_LEFT,
//       TileName.GROUND_TOP_MIDDLE,
//       TileName.GROUND_TOP_RIGHT,
//     ],
//     [
//       TileName.WATER_MIDDLE_MIDDLE,
//       TileName.GROUND_TOP_RIGHT,
//       TileName.GROUND_MIDDLE_RIGHT,
//       TileName.GROUND_BOTTOM_RIGHT,
//     ],
//   ],
//   [TileName.GROUND_TOP_LEFT]: [
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.GROUND_TOP_MIDDLE, TileName.GROUND_TOP_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_TOP_MIDDLE]: [
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.GROUND_TOP_MIDDLE, TileName.GROUND_TOP_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_TOP_MIDDLE, TileName.GROUND_TOP_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_TOP_RIGHT]: [
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_BOTTOM_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_TOP_MIDDLE, TileName.GROUND_TOP_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_MIDDLE_LEFT]: [
//     [TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_TOP_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_MIDDLE_MIDDLE]: [
//     [TileName.GROUND_MIDDLE_MIDDLE, TileName.GROUND_TOP_MIDDLE, TileName.GROUND_TOP_LEFT, TileName.GROUND_TOP_RIGHT, TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_MIDDLE_RIGHT],
//     [TileName.GROUND_MIDDLE_MIDDLE, TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_TOP_RIGHT, TileName.GROUND_TOP_MIDDLE, TileName.GROUND_BOTTOM_RIGHT, TileName.GROUND_BOTTOM_MIDDLE],
//     [TileName.GROUND_MIDDLE_MIDDLE, TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_BOTTOM_RIGHT],
//     [TileName.GROUND_MIDDLE_MIDDLE, TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_TOP_LEFT, TileName.GROUND_TOP_MIDDLE, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_BOTTOM_MIDDLE],
//   ],
//   [TileName.GROUND_MIDDLE_RIGHT]: [
//     [TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_TOP_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_BOTTOM_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_BOTTOM_LEFT]: [
//     [TileName.GROUND_TOP_LEFT, TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_BOTTOM_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_BOTTOM_MIDDLE]: [
//     [TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_BOTTOM_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//   ],
//   [TileName.GROUND_BOTTOM_RIGHT]: [
//     [TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_TOP_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.WATER_MIDDLE_MIDDLE],
//     [TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
//   ],
// };

export const TILE_TYPES_SIMPLE = [
  TileName.WATER_MIDDLE_MIDDLE,
  TileName.GROUND_TOP_LEFT,
  TileName.GROUND_TOP_RIGHT,
  TileName.GROUND_BOTTOM_LEFT,
  TileName.GROUND_BOTTOM_RIGHT,
];

export const RULES_SIMPLE = {
  [TileName.WATER_MIDDLE_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE, TileName.GROUND_BOTTOM_LEFT, TileName.GROUND_BOTTOM_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE, TileName.GROUND_TOP_LEFT, TileName.GROUND_BOTTOM_LEFT],
    [TileName.WATER_MIDDLE_MIDDLE, TileName.GROUND_TOP_LEFT, TileName.GROUND_TOP_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE, TileName.GROUND_TOP_RIGHT, TileName.GROUND_BOTTOM_RIGHT],
  ],
  [TileName.GROUND_TOP_LEFT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.GROUND_TOP_RIGHT],
    [TileName.GROUND_BOTTOM_LEFT],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_TOP_RIGHT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.GROUND_BOTTOM_RIGHT],
    [TileName.GROUND_TOP_LEFT],
  ],
  [TileName.GROUND_BOTTOM_LEFT]: [
    [TileName.GROUND_TOP_LEFT],
    [TileName.GROUND_BOTTOM_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_BOTTOM_RIGHT]: [
    [TileName.GROUND_TOP_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.GROUND_BOTTOM_LEFT],
  ],
};

export const RULES = {
  [TileName.WATER_MIDDLE_MIDDLE]: [
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_MIDDLE,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_BOTTOM_LEFT,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.BRIDGE_MIDDLE,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
  ],
  [TileName.GROUND_TOP_LEFT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_TOP_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.GROUND_TOP_RIGHT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_LEFT,
    ],
  ],
  [TileName.GROUND_MIDDLE_LEFT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_MIDDLE_MIDDLE]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_RIGHT,
    ],
  ],
  [TileName.GROUND_MIDDLE_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_RIGHT,
    ],
  ],
  [TileName.GROUND_BOTTOM_LEFT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_BOTTOM_MIDDLE]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.GROUND_BOTTOM_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.BRIDGE_LEFT]: [
    [
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [TileName.BRIDGE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
    ],
  ],
  [TileName.BRIDGE_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.BRIDGE_MIDDLE, TileName.BRIDGE_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.BRIDGE_MIDDLE, TileName.BRIDGE_LEFT],
  ],
  [TileName.BRIDGE_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_MIDDLE_LEFT,
    ],
    [
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_BOTTOM_LEFT,
    ],
    [
      TileName.BRIDGE_MIDDLE,
      TileName.BRIDGE_LEFT
    ],
  ]
};