import { LayerRules, SpriteWeight } from "@core/layer";
import { SpriteName } from "@core/renderer";

export const STONES_WEIGHT: SpriteWeight[] = [
  [SpriteName.WATER_MIDDLE_MIDDLE,  1, true],

  [SpriteName.ELEVATION_TOP_LEFT,      1, false],
  [SpriteName.ELEVATION_TOP_MIDDLE,    10, false],
  [SpriteName.ELEVATION_TOP_RIGHT,     1, false],
  [SpriteName.ELEVATION_MIDDLE_LEFT,   10, false],
  [SpriteName.ELEVATION_MIDDLE_MIDDLE, 100, false],
  [SpriteName.ELEVATION_MIDDLE_RIGHT,  10, false],
  [SpriteName.ELEVATION_BOTTOM_LEFT,   1, false],
  [SpriteName.ELEVATION_BOTTOM_MIDDLE, 10, false],
  [SpriteName.ELEVATION_BOTTOM_RIGHT,  1, false],

  [SpriteName.BRIDGE_LEFT,          1, false],
  [SpriteName.BRIDGE_MIDDLE,        1, false],
  [SpriteName.BRIDGE_RIGHT,         1, false],
];

export const STONES_RULES: LayerRules = {
  [SpriteName.WATER_MIDDLE_MIDDLE]: [
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
      SpriteName.BRIDGE_MIDDLE,
    ],
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
    ],
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.BRIDGE_MIDDLE,
    ],
    [
      SpriteName.WATER_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
  ],
  [SpriteName.ELEVATION_TOP_LEFT]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
  ],
  [SpriteName.ELEVATION_TOP_MIDDLE]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
    ],
  ],
  [SpriteName.ELEVATION_TOP_RIGHT]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.BRIDGE_LEFT,
    ],
  ],
  [SpriteName.ELEVATION_MIDDLE_LEFT]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
  ],
  [SpriteName.ELEVATION_MIDDLE_MIDDLE]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.BRIDGE_RIGHT,
    ],
  ],
  [SpriteName.ELEVATION_MIDDLE_RIGHT]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.BRIDGE_RIGHT,
    ],
  ],
  [SpriteName.ELEVATION_BOTTOM_LEFT]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.BRIDGE_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.WATER_MIDDLE_MIDDLE],
  ],
  [SpriteName.ELEVATION_BOTTOM_MIDDLE]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
    ],
    [
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
    ],
  ],
  [SpriteName.ELEVATION_BOTTOM_RIGHT]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.BRIDGE_LEFT,
    ],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_TOP_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_BOTTOM_LEFT,
      SpriteName.ELEVATION_BOTTOM_MIDDLE,
    ],
  ],
  [SpriteName.BRIDGE_LEFT]: [
    [
      SpriteName.ELEVATION_TOP_RIGHT,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
    ],
    [SpriteName.BRIDGE_MIDDLE],
    [
      SpriteName.ELEVATION_MIDDLE_RIGHT,
      SpriteName.ELEVATION_BOTTOM_RIGHT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_LEFT,
    ],
  ],
  [SpriteName.BRIDGE_MIDDLE]: [
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.BRIDGE_MIDDLE, SpriteName.BRIDGE_RIGHT],
    [SpriteName.WATER_MIDDLE_MIDDLE],
    [SpriteName.BRIDGE_MIDDLE, SpriteName.BRIDGE_LEFT],
  ],
  [SpriteName.BRIDGE_RIGHT]: [
    [
      SpriteName.ELEVATION_TOP_LEFT,
      SpriteName.ELEVATION_MIDDLE_LEFT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_MIDDLE,
      SpriteName.ELEVATION_MIDDLE_RIGHT,
    ],
    [
      SpriteName.ELEVATION_MIDDLE_LEFT,
      SpriteName.ELEVATION_BOTTOM_LEFT,
    ],
    [
      SpriteName.BRIDGE_MIDDLE,
      SpriteName.BRIDGE_LEFT
    ],
  ],
};