import { TileName } from "../../renderer/renderer.const";

export const LAYER_MAIN_WEIGHT = [
  [TileName.WATER_MIDDLE_MIDDLE,  1],
  [TileName.GROUND_TOP_LEFT,      10],
  [TileName.GROUND_TOP_MIDDLE,    10],
  [TileName.GROUND_TOP_RIGHT,     10],
  [TileName.GROUND_MIDDLE_LEFT,   10],
  [TileName.GROUND_MIDDLE_MIDDLE, 100],
  [TileName.GROUND_MIDDLE_RIGHT,  10],
  [TileName.GROUND_BOTTOM_LEFT,   10],
  [TileName.GROUND_BOTTOM_MIDDLE, 10],
  [TileName.GROUND_BOTTOM_RIGHT,  10],
  [TileName.BRIDGE_LEFT,          20],
  [TileName.BRIDGE_MIDDLE,        20],
  [TileName.BRIDGE_RIGHT,         20],
  [TileName.TREE_STRUMP,          10],
];

/*
  TileName.GROUND_TOP_LEFT,
  TileName.GROUND_TOP_MIDDLE,
  TileName.GROUND_TOP_RIGHT,
  TileName.GROUND_MIDDLE_LEFT,
  TileName.GROUND_MIDDLE_MIDDLE,
  TileName.GROUND_MIDDLE_RIGHT,
  TileName.GROUND_BOTTOM_LEFT,
  TileName.GROUND_BOTTOM_MIDDLE
  TileName.GROUND_BOTTOM_RIGHT,
*/
export const LAYER_MAIN_RULES = {
  [TileName.WATER_MIDDLE_MIDDLE]: [
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_MIDDLE,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_BOTTOM_LEFT,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.BRIDGE_MIDDLE,
    ],
    [
      TileName.WATER_MIDDLE_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
  ],
  [TileName.GROUND_TOP_LEFT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_TOP_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.GROUND_TOP_RIGHT]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_LEFT,
    ],
  ],
  [TileName.GROUND_MIDDLE_LEFT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_MIDDLE_MIDDLE]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_RIGHT,
      TileName.TREE_STRUMP,
    ],
  ],
  [TileName.GROUND_MIDDLE_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.BRIDGE_RIGHT,
      TileName.TREE_STRUMP,
    ],
  ],
  [TileName.GROUND_BOTTOM_LEFT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_RIGHT,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
  ],
  [TileName.GROUND_BOTTOM_MIDDLE]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.TREE_STRUMP,
    ],
    [
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_MIDDLE,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.GROUND_BOTTOM_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.BRIDGE_LEFT,
    ],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.WATER_MIDDLE_MIDDLE],
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_TOP_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_BOTTOM_LEFT,
      TileName.GROUND_BOTTOM_MIDDLE,
    ],
  ],
  [TileName.BRIDGE_LEFT]: [
    [
      TileName.GROUND_TOP_RIGHT,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [TileName.BRIDGE_MIDDLE],
    [
      TileName.GROUND_MIDDLE_RIGHT,
      TileName.GROUND_BOTTOM_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_LEFT,
    ],
  ],
  [TileName.BRIDGE_MIDDLE]: [
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.BRIDGE_MIDDLE, TileName.BRIDGE_RIGHT],
    [TileName.WATER_MIDDLE_MIDDLE],
    [TileName.BRIDGE_MIDDLE, TileName.BRIDGE_LEFT],
  ],
  [TileName.BRIDGE_RIGHT]: [
    [
      TileName.GROUND_TOP_LEFT,
      TileName.GROUND_MIDDLE_LEFT,
    ],
    [
      TileName.GROUND_MIDDLE_MIDDLE,
      TileName.GROUND_MIDDLE_RIGHT,
    ],
    [
      TileName.GROUND_MIDDLE_LEFT,
      TileName.GROUND_BOTTOM_LEFT,
    ],
    [
      TileName.BRIDGE_MIDDLE,
      TileName.BRIDGE_LEFT
    ],
  ],
  [TileName.TREE_STRUMP]: [
    [TileName.GROUND_TOP_MIDDLE, TileName.GROUND_MIDDLE_MIDDLE],
    [TileName.GROUND_MIDDLE_RIGHT, TileName.GROUND_MIDDLE_MIDDLE],
    [TileName.GROUND_BOTTOM_MIDDLE, TileName.GROUND_MIDDLE_MIDDLE],
    [TileName.GROUND_MIDDLE_LEFT, TileName.GROUND_MIDDLE_MIDDLE],
  ],
};