import { ElevationSprite, ElevationType } from '@entities/elevation';
import { GroundSprite, GroundType } from '@entities/ground';
import { SandSprite, SandType } from '@entities/sand';
import { FoamSprite, FoamType } from '@entities/foam';
import { WaterSprite } from '@entities/water';
import { BridgeSprite, BridgeType } from '@entities/bridge';
import { DecoSprite, DecoType } from '@entities/deco';
import { RocksSprite, RocksType } from '@entities/rocks';
import { TreeSprite, TreeType } from '@entities/tree';
import { HouseSprite, HouseType } from '@entities/house';
import { BoundarySprite, BoundaryType } from '@entities/boundary';
import { GoldMineSprite, GoldMineType } from '@entities/gold-mine';
import { SheepSprite, SheepType } from '@entities/sheep';
import { TowerSprite, TowerType } from '@entities/tower';

export const enum SpriteName {
  WATER_MIDDLE_MIDDLE,

  SAND_TOP_LEFT,
  SAND_TOP_MIDDLE,
  SAND_TOP_RIGHT,
  SAND_BOTTOM_LEFT,
  SAND_BOTTOM_MIDDLE,
  SAND_BOTTOM_RIGHT,
  SAND_MIDDLE_LEFT,
  SAND_MIDDLE_MIDDLE,
  SAND_MIDDLE_RIGHT,
  SAND_HORIZONTAL_LEFT,
  SAND_HORIZONTAL_MIDDLE,
  SAND_HORIZONTAL_RIGHT,
  SAND_VERTICAL_TOP,
  SAND_VERTICAL_MIDDLE,
  SAND_VERTICAL_BOTTOM,

  GROUND_TOP_LEFT,
  GROUND_TOP_MIDDLE,
  GROUND_TOP_RIGHT,
  GROUND_BOTTOM_LEFT,
  GROUND_BOTTOM_MIDDLE,
  GROUND_BOTTOM_RIGHT,
  GROUND_MIDDLE_LEFT,
  GROUND_MIDDLE_MIDDLE,
  GROUND_MIDDLE_RIGHT,
  GROUND_HORIZONTAL_LEFT,
  GROUND_HORIZONTAL_MIDDLE,
  GROUND_HORIZONTAL_RIGHT,
  GROUND_VERTICAL_TOP,
  GROUND_VERTICAL_MIDDLE,
  GROUND_VERTICAL_BOTTOM,

  ELEVATION_TOP_LEFT,
  ELEVATION_TOP_MIDDLE,
  ELEVATION_TOP_RIGHT,
  ELEVATION_BOTTOM_LEFT,
  ELEVATION_BOTTOM_MIDDLE,
  ELEVATION_BOTTOM_RIGHT,
  ELEVATION_MIDDLE_LEFT,
  ELEVATION_MIDDLE_MIDDLE,
  ELEVATION_MIDDLE_RIGHT,
  ELEVATION_HORIZONTAL_LEFT,
  ELEVATION_HORIZONTAL_MIDDLE,
  ELEVATION_HORIZONTAL_RIGHT,
  ELEVATION_VERTICAL_TOP,
  ELEVATION_VERTICAL_MIDDLE,
  ELEVATION_VERTICAL_BOTTOM,
  ELEVATION_VERTICAL_EDGE,
  ELEVATION_EDGE_LEFT,
  ELEVATION_EDGE_MIDDLE,
  ELEVATION_EDGE_RIGHT,

  FOAM_TOP,
  FOAM_LEFT,
  FOAM_RIGHT,
  FOAM_BOTTOM,
  FOAM_MIDDLE,

  BRIDGE_LEFT,
  BRIDGE_MIDDLE,
  BRIDGE_RIGHT,
  BRIDGE_SHADOW,

  DECO_MUSHROOM_S,
  DECO_MUSHROOM_M,
  DECO_MUSHROOM_L,
  DECO_STONE_S,
  DECO_STONE_M,
  DECO_STONE_L,
  DECO_BUSH_S,
  DECO_BUSH_M,
  DECO_BUSH_L,
  DECO_WEED_S,
  DECO_WEED_M,
  DECO_PUMPKIN_S,
  DECO_PUMPKIN_M,

  DECO_BONE_S_RIGHT,
  DECO_BONE_S_LEFT,
  DECO_BONE_M_RIGHT,
  DECO_BONE_M_LEFT,
  DECO_SIGN_STOP_TOP,
  DECO_SIGN_STOP_BOTTOM,
  DECO_SIGH_RIGHT_TOP,
  DECO_SIGH_RIGHT_BOTTOM,
  DECO_SCARECROW,
  DECO_SKULL_RIGHT,
  DECO_SKULL_LEFT,

  ROCKS_S,
  ROCKS_M,
  ROCKS_L,

  SHEEP_RIGHT,
  SHEEP_LEFT,

  TREE_TOP_LEFT,
  TREE_TOP_MIDDLE,
  TREE_TOP_RIGHT,
  TREE_MIDDLE_LEFT,
  TREE_MIDDLE_MIDDLE,
  TREE_MIDDLE_RIGHT,
  TREE_BOTTOM_LEFT,
  TREE_BOTTOM_MIDDLE,
  TREE_BOTTOM_RIGHT,
  TREE_STRUMP,

  HOUSE_TOP_LEFT,
  HOUSE_TOP_RIGHT,
  HOUSE_MIDDLE_LEFT,
  HOUSE_MIDDLE_RIGHT,
  HOUSE_BOTTOM_LEFT,
  HOUSE_BOTTOM_RIGHT,

  TOWER_TOP_LEFT,
  TOWER_TOP_RIGHT,
  TOWER_MIDDLE_LEFT,
  TOWER_MIDDLE_RIGHT,
  TOWER_BOTTOM_LEFT,
  TOWER_BOTTOM_RIGHT,

  GOLDMINE_TOP_LEFT,
  GOLDMINE_TOP_MIDDLE,
  GOLDMINE_TOP_RIGHT,
  GOLDMINE_BOTTOM_LEFT,
  GOLDMINE_BOTTOM_MIDDLE,
  GOLDMINE_BOTTOM_RIGHT,

  BOUNDARY,
}

export const mapSpriteNameToClass: Partial<Record<SpriteName, { constructor: any; args: Array<any> }>> = {
  [SpriteName.WATER_MIDDLE_MIDDLE]: { constructor: WaterSprite, args: [] },

  [SpriteName.SAND_TOP_LEFT]: { constructor: SandSprite, args: [SandType.TOP_LEFT] },
  [SpriteName.SAND_TOP_MIDDLE]: { constructor: SandSprite, args: [SandType.TOP_MIDDLE] },
  [SpriteName.SAND_TOP_RIGHT]: { constructor: SandSprite, args: [SandType.TOP_RIGHT] },
  [SpriteName.SAND_BOTTOM_LEFT]: { constructor: SandSprite, args: [SandType.BOTTOM_LEFT] },
  [SpriteName.SAND_BOTTOM_MIDDLE]: { constructor: SandSprite, args: [SandType.BOTTOM_MIDDLE] },
  [SpriteName.SAND_BOTTOM_RIGHT]: { constructor: SandSprite, args: [SandType.BOTTOM_RIGHT] },
  [SpriteName.SAND_MIDDLE_LEFT]: { constructor: SandSprite, args: [SandType.MIDDLE_LEFT] },
  [SpriteName.SAND_MIDDLE_MIDDLE]: { constructor: SandSprite, args: [SandType.MIDDLE_MIDDLE] },
  [SpriteName.SAND_MIDDLE_RIGHT]: { constructor: SandSprite, args: [SandType.MIDDLE_RIGHT] },
  [SpriteName.SAND_VERTICAL_TOP]: { constructor: SandSprite, args: [SandType.VERTICAL_TOP] },
  [SpriteName.SAND_VERTICAL_MIDDLE]: { constructor: SandSprite, args: [SandType.VERTICAL_MIDDLE] },
  [SpriteName.SAND_VERTICAL_BOTTOM]: { constructor: SandSprite, args: [SandType.VERTICAL_BOTTOM] },
  [SpriteName.SAND_HORIZONTAL_LEFT]: { constructor: SandSprite, args: [SandType.HORIZONTAL_LEFT] },
  [SpriteName.SAND_HORIZONTAL_MIDDLE]: { constructor: SandSprite, args: [SandType.HORIZONTAL_MIDDLE] },
  [SpriteName.SAND_HORIZONTAL_RIGHT]: { constructor: SandSprite, args: [SandType.HORIZONTAL_RIGHT] },

  [SpriteName.GROUND_TOP_LEFT]: { constructor: GroundSprite, args: [GroundType.TOP_LEFT] },
  [SpriteName.GROUND_TOP_MIDDLE]: { constructor: GroundSprite, args: [GroundType.TOP_MIDDLE] },
  [SpriteName.GROUND_TOP_RIGHT]: { constructor: GroundSprite, args: [GroundType.TOP_RIGHT] },
  [SpriteName.GROUND_BOTTOM_LEFT]: { constructor: GroundSprite, args: [GroundType.BOTTOM_LEFT] },
  [SpriteName.GROUND_BOTTOM_MIDDLE]: { constructor: GroundSprite, args: [GroundType.BOTTOM_MIDDLE] },
  [SpriteName.GROUND_BOTTOM_RIGHT]: { constructor: GroundSprite, args: [GroundType.BOTTOM_RIGHT] },
  [SpriteName.GROUND_MIDDLE_LEFT]: { constructor: GroundSprite, args: [GroundType.MIDDLE_LEFT] },
  [SpriteName.GROUND_MIDDLE_MIDDLE]: { constructor: GroundSprite, args: [GroundType.MIDDLE_MIDDLE] },
  [SpriteName.GROUND_MIDDLE_RIGHT]: { constructor: GroundSprite, args: [GroundType.MIDDLE_RIGHT] },
  [SpriteName.GROUND_HORIZONTAL_LEFT]: { constructor: GroundSprite, args: [GroundType.HORIZONTAL_LEFT] },
  [SpriteName.GROUND_HORIZONTAL_MIDDLE]: { constructor: GroundSprite, args: [GroundType.HORIZONTAL_MIDDLE] },
  [SpriteName.GROUND_HORIZONTAL_RIGHT]: { constructor: GroundSprite, args: [GroundType.HORIZONTAL_RIGHT] },
  [SpriteName.GROUND_VERTICAL_TOP]: { constructor: GroundSprite, args: [GroundType.VERTICAL_TOP] },
  [SpriteName.GROUND_VERTICAL_MIDDLE]: { constructor: GroundSprite, args: [GroundType.VERTICAL_MIDDLE] },
  [SpriteName.GROUND_VERTICAL_BOTTOM]: { constructor: GroundSprite, args: [GroundType.VERTICAL_BOTTOM] },

  [SpriteName.ELEVATION_TOP_LEFT]: { constructor: ElevationSprite, args: [ElevationType.TOP_LEFT] },
  [SpriteName.ELEVATION_TOP_MIDDLE]: { constructor: ElevationSprite, args: [ElevationType.TOP_MIDDLE] },
  [SpriteName.ELEVATION_TOP_RIGHT]: { constructor: ElevationSprite, args: [ElevationType.TOP_RIGHT] },
  [SpriteName.ELEVATION_BOTTOM_LEFT]: { constructor: ElevationSprite, args: [ElevationType.BOTTOM_LEFT] },
  [SpriteName.ELEVATION_BOTTOM_MIDDLE]: { constructor: ElevationSprite, args: [ElevationType.BOTTOM_MIDDLE] },
  [SpriteName.ELEVATION_BOTTOM_RIGHT]: { constructor: ElevationSprite, args: [ElevationType.BOTTOM_RIGHT] },
  [SpriteName.ELEVATION_MIDDLE_LEFT]: { constructor: ElevationSprite, args: [ElevationType.MIDDLE_LEFT] },
  [SpriteName.ELEVATION_MIDDLE_MIDDLE]: { constructor: ElevationSprite, args: [ElevationType.MIDDLE_MIDDLE] },
  [SpriteName.ELEVATION_MIDDLE_RIGHT]: { constructor: ElevationSprite, args: [ElevationType.MIDDLE_RIGHT] },
  [SpriteName.ELEVATION_HORIZONTAL_LEFT]: { constructor: ElevationSprite, args: [ElevationType.HORIZONTAL_LEFT] },
  [SpriteName.ELEVATION_HORIZONTAL_MIDDLE]: { constructor: ElevationSprite, args: [ElevationType.HORIZONTAL_MIDDLE] },
  [SpriteName.ELEVATION_HORIZONTAL_RIGHT]: { constructor: ElevationSprite, args: [ElevationType.HORIZONTAL_RIGHT] },
  [SpriteName.ELEVATION_VERTICAL_TOP]: { constructor: ElevationSprite, args: [ElevationType.VERTICAL_TOP] },
  [SpriteName.ELEVATION_VERTICAL_MIDDLE]: { constructor: ElevationSprite, args: [ElevationType.VERTICAL_MIDDLE] },
  [SpriteName.ELEVATION_VERTICAL_BOTTOM]: { constructor: ElevationSprite, args: [ElevationType.VERTICAL_BOTTOM] },
  [SpriteName.ELEVATION_VERTICAL_EDGE]: { constructor: ElevationSprite, args: [ElevationType.VERTICAL_EDGE] },
  [SpriteName.ELEVATION_EDGE_LEFT]: { constructor: ElevationSprite, args: [ElevationType.EDGE_LEFT] },
  [SpriteName.ELEVATION_EDGE_MIDDLE]: { constructor: ElevationSprite, args: [ElevationType.EDGE_MIDDLE] },
  [SpriteName.ELEVATION_EDGE_RIGHT]: { constructor: ElevationSprite, args: [ElevationType.EDGE_RIGHT] },

  [SpriteName.BRIDGE_LEFT]: { constructor: BridgeSprite, args: [BridgeType.LEFT] },
  [SpriteName.BRIDGE_MIDDLE]: { constructor: BridgeSprite, args: [BridgeType.MIDDLE] },
  [SpriteName.BRIDGE_RIGHT]: { constructor: BridgeSprite, args: [BridgeType.RIGHT] },
  [SpriteName.BRIDGE_SHADOW]: { constructor: BridgeSprite, args: [BridgeType.SHADOW] },

  [SpriteName.FOAM_TOP]: { constructor: FoamSprite, args: [FoamType.TOP] },
  [SpriteName.FOAM_LEFT]: { constructor: FoamSprite, args: [FoamType.LEFT] },
  [SpriteName.FOAM_RIGHT]: { constructor: FoamSprite, args: [FoamType.RIGHT] },
  [SpriteName.FOAM_BOTTOM]: { constructor: FoamSprite, args: [FoamType.BOTTOM] },
  [SpriteName.FOAM_MIDDLE]: { constructor: FoamSprite, args: [FoamType.MIDDLE] },

  [SpriteName.DECO_MUSHROOM_S]: { constructor: DecoSprite, args: [DecoType.MUSHROOM_S] },
  [SpriteName.DECO_MUSHROOM_M]: { constructor: DecoSprite, args: [DecoType.MUSHROOM_M] },
  [SpriteName.DECO_MUSHROOM_L]: { constructor: DecoSprite, args: [DecoType.MUSHROOM_L] },
  [SpriteName.DECO_STONE_S]: { constructor: DecoSprite, args: [DecoType.STONE_S] },
  [SpriteName.DECO_STONE_M]: { constructor: DecoSprite, args: [DecoType.STONE_M] },
  [SpriteName.DECO_STONE_L]: { constructor: DecoSprite, args: [DecoType.STONE_L] },
  [SpriteName.DECO_BUSH_S]: { constructor: DecoSprite, args: [DecoType.BUSH_S] },
  [SpriteName.DECO_BUSH_M]: { constructor: DecoSprite, args: [DecoType.BUSH_M] },
  [SpriteName.DECO_BUSH_L]: { constructor: DecoSprite, args: [DecoType.BUSH_L] },
  [SpriteName.DECO_WEED_S]: { constructor: DecoSprite, args: [DecoType.WEED_S] },
  [SpriteName.DECO_WEED_M]: { constructor: DecoSprite, args: [DecoType.WEED_M] },
  [SpriteName.DECO_PUMPKIN_S]: { constructor: DecoSprite, args: [DecoType.PUMPKIN_S] },
  [SpriteName.DECO_PUMPKIN_M]: { constructor: DecoSprite, args: [DecoType.PUMPKIN_M] },
  [SpriteName.DECO_BONE_S_RIGHT]: { constructor: DecoSprite, args: [DecoType.BONE_S_RIGHT] },
  [SpriteName.DECO_BONE_S_LEFT]: { constructor: DecoSprite, args: [DecoType.BONE_S_LEFT] },
  [SpriteName.DECO_BONE_M_RIGHT]: { constructor: DecoSprite, args: [DecoType.BONE_M_RIGHT] },
  [SpriteName.DECO_BONE_M_LEFT]: { constructor: DecoSprite, args: [DecoType.BONE_M_LEFT] },
  [SpriteName.DECO_SIGN_STOP_TOP]: { constructor: DecoSprite, args: [DecoType.SIGN_STOP_TOP] },
  [SpriteName.DECO_SIGN_STOP_BOTTOM]: { constructor: DecoSprite, args: [DecoType.SIGN_STOP_BOTTOM] },
  [SpriteName.DECO_SIGH_RIGHT_TOP]: { constructor: DecoSprite, args: [DecoType.SIGH_RIGHT_TOP] },
  [SpriteName.DECO_SIGH_RIGHT_BOTTOM]: { constructor: DecoSprite, args: [DecoType.SIGH_RIGHT_BOTTOM] },
  [SpriteName.DECO_SCARECROW]: { constructor: DecoSprite, args: [DecoType.SCARECROW] },
  [SpriteName.DECO_SKULL_RIGHT]: { constructor: DecoSprite, args: [DecoType.SKULL_RIGHT] },
  [SpriteName.DECO_SKULL_LEFT]: { constructor: DecoSprite, args: [DecoType.SKULL_LEFT] },

  [SpriteName.ROCKS_S]: { constructor: RocksSprite, args: [RocksType.ROCKS_S] },
  [SpriteName.ROCKS_M]: { constructor: RocksSprite, args: [RocksType.ROCKS_M] },
  [SpriteName.ROCKS_L]: { constructor: RocksSprite, args: [RocksType.ROCKS_L] },

  [SpriteName.SHEEP_RIGHT]: { constructor: SheepSprite, args: [SheepType.SHEEP_RIGHT] },
  [SpriteName.SHEEP_LEFT]: { constructor: SheepSprite, args: [SheepType.SHEEP_LEFT] },

  [SpriteName.TREE_TOP_LEFT]: { constructor: TreeSprite, args: [TreeType.TOP_LEFT] },
  [SpriteName.TREE_TOP_MIDDLE]: { constructor: TreeSprite, args: [TreeType.TOP_MIDDLE] },
  [SpriteName.TREE_TOP_RIGHT]: { constructor: TreeSprite, args: [TreeType.TOP_RIGHT] },
  [SpriteName.TREE_MIDDLE_LEFT]: { constructor: TreeSprite, args: [TreeType.MIDDLE_LEFT] },
  [SpriteName.TREE_MIDDLE_MIDDLE]: { constructor: TreeSprite, args: [TreeType.MIDDLE_MIDDLE] },
  [SpriteName.TREE_MIDDLE_RIGHT]: { constructor: TreeSprite, args: [TreeType.MIDDLE_RIGHT] },
  [SpriteName.TREE_BOTTOM_LEFT]: { constructor: TreeSprite, args: [TreeType.BOTTOM_LEFT] },
  [SpriteName.TREE_BOTTOM_MIDDLE]: { constructor: TreeSprite, args: [TreeType.BOTTOM_MIDDLE] },
  [SpriteName.TREE_BOTTOM_RIGHT]: { constructor: TreeSprite, args: [TreeType.BOTTOM_RIGHT] },
  [SpriteName.TREE_STRUMP]: { constructor: TreeSprite, args: [TreeType.STRUMP] },

  [SpriteName.HOUSE_TOP_LEFT]: { constructor: HouseSprite, args: [HouseType.TOP_LEFT] },
  [SpriteName.HOUSE_TOP_RIGHT]: { constructor: HouseSprite, args: [HouseType.TOP_RIGHT] },
  [SpriteName.HOUSE_MIDDLE_LEFT]: { constructor: HouseSprite, args: [HouseType.MIDDLE_LEFT] },
  [SpriteName.HOUSE_MIDDLE_RIGHT]: { constructor: HouseSprite, args: [HouseType.MIDDLE_RIGHT] },
  [SpriteName.HOUSE_BOTTOM_LEFT]: { constructor: HouseSprite, args: [HouseType.BOTTOM_LEFT] },
  [SpriteName.HOUSE_BOTTOM_RIGHT]: { constructor: HouseSprite, args: [HouseType.BOTTOM_RIGHT] },

  [SpriteName.TOWER_TOP_LEFT]: { constructor: TowerSprite, args: [TowerType.TOP_LEFT] },
  [SpriteName.TOWER_TOP_RIGHT]: { constructor: TowerSprite, args: [TowerType.TOP_RIGHT] },
  [SpriteName.TOWER_MIDDLE_LEFT]: { constructor: TowerSprite, args: [TowerType.MIDDLE_LEFT] },
  [SpriteName.TOWER_MIDDLE_RIGHT]: { constructor: TowerSprite, args: [TowerType.MIDDLE_RIGHT] },
  [SpriteName.TOWER_BOTTOM_LEFT]: { constructor: TowerSprite, args: [TowerType.BOTTOM_LEFT] },
  [SpriteName.TOWER_BOTTOM_RIGHT]: { constructor: TowerSprite, args: [TowerType.BOTTOM_RIGHT] },

  [SpriteName.GOLDMINE_TOP_LEFT]: { constructor: GoldMineSprite, args: [GoldMineType.TOP_LEFT] },
  [SpriteName.GOLDMINE_TOP_MIDDLE]: { constructor: GoldMineSprite, args: [GoldMineType.TOP_MIDDLE] },
  [SpriteName.GOLDMINE_TOP_RIGHT]: { constructor: GoldMineSprite, args: [GoldMineType.TOP_RIGHT] },
  [SpriteName.GOLDMINE_BOTTOM_LEFT]: { constructor: GoldMineSprite, args: [GoldMineType.BOTTOM_LEFT] },
  [SpriteName.GOLDMINE_BOTTOM_MIDDLE]: { constructor: GoldMineSprite, args: [GoldMineType.BOTTOM_MIDDLE] },
  [SpriteName.GOLDMINE_BOTTOM_RIGHT]: { constructor: GoldMineSprite, args: [GoldMineType.BOTTOM_RIGHT] },

  [SpriteName.BOUNDARY]: { constructor: BoundarySprite, args: [BoundaryType.MIDDLE] },
};
