name: Tiny Swords CI

on:
  workflow_dispatch:
  push:

jobs:
  main:
    if: github.event.pull_request.merged == false
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: npx nx affected -t lint --parallel=3
      - name: Test
        run: npx nx affected -t test --parallel=3
      - name: Build
        run: npx nx run-many -t build -p backend tiny-swords
